// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-daily-brief.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.101.1";
function publicSupabase() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
async function latestSnapshots(limit = 1) {
  const { data, error } = await publicSupabase().from("spark_daily_snapshots").select("date, summary").order("date", { ascending: false }).limit(limit);
  if (error) throw new Error(error.message);
  return data ?? [];
}
function articlesOf(snapshot) {
  const s = snapshot?.summary ?? {};
  const list = (Array.isArray(s.all_articles) && s.all_articles.length > 0 ? s.all_articles : s.articles) ?? [];
  return list;
}
function text(payload) {
  return { content: [{ type: "text", text: JSON.stringify(payload, null, 2) }] };
}
function errorText(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}

// src/lib/mcp/tools/get-daily-brief.ts
var get_daily_brief_default = defineTool({
  name: "get_daily_brief",
  title: "Get daily brief",
  description: "Get the latest AI-curated big data ecosystem brief: top insight, key highlights, emerging trends, and why-it-matters impact lines.",
  inputSchema: {
    date: z.string().describe("Optional ISO date (YYYY-MM-DD). Omit for the most recent brief.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date }) => {
    try {
      const snapshots = await latestSnapshots(date ? 30 : 1);
      const snap = date ? snapshots.find((s2) => s2.date === date) : snapshots[0];
      if (!snap) return errorText(date ? `No brief found for ${date}.` : "No brief available yet.");
      const s = snap.summary ?? {};
      return text({
        date: snap.date,
        topInsight: s.topInsight ?? null,
        highlights: s.highlights ?? [],
        trends: s.trends ?? [],
        impact: s.impact ?? []
      });
    } catch (e) {
      return errorText(String(e));
    }
  }
});

// src/lib/mcp/tools/list-articles.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var list_articles_default = defineTool2({
  name: "list_articles",
  title: "List articles",
  description: "List the most recently ingested big data ecosystem articles (Databricks, Spark, Iceberg, Delta, Fabric, EMR, BigQuery, Google Cloud) with title, source, summary, tags and link.",
  inputSchema: {
    limit: z2.number().int().describe("Max articles to return (1-40). Default 15.").optional(),
    source: z2.string().describe("Optional source filter, e.g. 'databricks' or 'google'.").optional(),
    days: z2.number().int().describe("How many recent days of snapshots to scan. Default 3.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, source, days }) => {
    try {
      const max = Math.min(Math.max(limit ?? 15, 1), 40);
      const snapshots = await latestSnapshots(Math.min(Math.max(days ?? 3, 1), 10));
      const seen = /* @__PURE__ */ new Set();
      const out = [];
      for (const snap of snapshots) {
        for (const a of articlesOf(snap)) {
          const key = a?.link ?? a?.title;
          if (!key || seen.has(key)) continue;
          if (source && !String(a.source ?? "").toLowerCase().includes(source.toLowerCase())) continue;
          seen.add(key);
          out.push({
            title: a.title,
            source: a.source,
            summary: a.summary,
            tags: a.tags,
            link: a.link,
            date: snap.date
          });
          if (out.length >= max) break;
        }
        if (out.length >= max) break;
      }
      return text({ count: out.length, articles: out });
    } catch (e) {
      return errorText(String(e));
    }
  }
});

// src/lib/mcp/tools/get-topic-trends.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_topic_trends_default = defineTool3({
  name: "get_topic_trends",
  title: "Get topic trends",
  description: "Get today's tracked big data topics with momentum status (growing, declining, new, stable), mention counts and day-over-day change.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    try {
      const [snap] = await latestSnapshots(1);
      if (!snap) return errorText("No trend data available yet.");
      const s = snap.summary ?? {};
      const trends = Array.isArray(s.topic_trends) ? s.topic_trends : s.trendItems ?? s.trends ?? [];
      return text({ date: snap.date, trends });
    } catch (e) {
      return errorText(String(e));
    }
  }
});

// src/lib/mcp/tools/search-articles.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var search_articles_default = defineTool4({
  name: "search_articles",
  title: "Search articles",
  description: "Keyword-search recently ingested big data ecosystem articles by title, summary or tag (e.g. 'iceberg', 'lakehouse', 'agentic').",
  inputSchema: {
    query: z3.string().describe("Keyword or phrase to search for."),
    limit: z3.number().int().describe("Max results (1-25). Default 10.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    try {
      const q = query.trim().toLowerCase();
      if (!q) return errorText("query must not be empty.");
      const max = Math.min(Math.max(limit ?? 10, 1), 25);
      const snapshots = await latestSnapshots(10);
      const seen = /* @__PURE__ */ new Set();
      const out = [];
      for (const snap of snapshots) {
        for (const a of articlesOf(snap)) {
          const key = a?.link ?? a?.title;
          if (!key || seen.has(key)) continue;
          const hay = `${a.title ?? ""} ${a.summary ?? ""} ${(a.tags ?? []).join(" ")}`.toLowerCase();
          if (!hay.includes(q)) continue;
          seen.add(key);
          out.push({ title: a.title, source: a.source, summary: a.summary, tags: a.tags, link: a.link, date: snap.date });
          if (out.length >= max) break;
        }
        if (out.length >= max) break;
      }
      return text({ query, count: out.length, articles: out });
    } catch (e) {
      return errorText(String(e));
    }
  }
});

// src/lib/mcp/index.ts
var projectRef = "dpjzypvarubkomehrwht";
var mcp_default = defineMcp({
  name: "bigdata-hub-mcp",
  title: "Big Data Intelligence Hub",
  version: "0.1.0",
  instructions: "Read-only intelligence tools for the Big Data Intelligence Hub. Use `get_daily_brief` for today's executive summary, `get_topic_trends` for topic momentum, `list_articles` for the latest ingested vendor blog posts, and `search_articles` to find posts by keyword. Data covers Databricks, Apache Spark, Iceberg, Delta Lake, Microsoft Fabric, AWS EMR, BigQuery and Google Cloud.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_daily_brief_default, get_topic_trends_default, list_articles_default, search_articles_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
